### ISSUE TITLE
CODE no valid to invoke TOKEN webservice.

### ISSUE THREAD

**Issue by juanise** [Roambi/roambi-api-docs#1]
Hi !!

I have a problem when I use the webservice (ws) /token. First of all, I invoke /Authorize ws but I receive a string in the parameter CODE so I need to send a number in the code param in the ws /Token, How can I convert the string code into numeric code? Which is the codification of string code that I get in Authorize ws?

Examples:

The request of /Authorize is:

```
{"username": "xxxxxx@xxx.xx",
    "password": "xxxxxx",
    "client_id": "xxxxxxxxxxxxxxxxxxxxxxxxx",
    "client_secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "redirect_uri": "http://www.xxxx.es/",
    "response_type": "code"
}
```

The response is something like that:
http://www.xxxx.es/?code=1%2Ffe0a602e254ce5c5885e27f356b8691780a56b18%7Cc6d39598e342b0e9c9017be641abf4c4a4a6292d

Thanks in advance.

**Comment by juanise** [comment]
I found the solution in the sdk code 
I just have to parse it : URLEncodedUtils.parse(redirectUri, "utf-8");
that give me a String like this:
1/fe0a602e254ce5c5885e27f356b8691780a56b18|c6d39598e342b0e9c9017be641abf4c4a4a6292d

And thats all i need to send /token request. 

I thougt that I must to send a number not a String because of roambi-api-docs

Parameter   Data                       type Description
.....
code           numeric   Authorization code that you previously retrieved.
......

Thank you.anyway.

**Comment by kirvin** [comment]
Yes, you just need to send the same string back to the token resource.

I will update our docs, as they appear to be incorrect.  Thank you for pointing this out.

**Comment by kirvin** [comment]
I have updated the docs here to more clearly describe the "code" parameter for the /token resource:  https://github.com/Roambi/roambi-api-docs/wiki/2.2-Access-Token-and-Refresh-Token

Thanks again for noticing this.
