### ISSUE TITLE
Create a new rbi from .xls

### ISSUE THREAD

**Issue by juanise** [Roambi/roambi-api-docs#10]
Hi, i'am trying to create a new Trends rbi from a new uploaded xls file.
I'm not sure if i can achieve this with method
                        POST /1/accounts/${ACCOUNT_UID}/files/analytics
If the answer is yes, how can I get template_uid parameter?

Thanks.

**Comment by charlesweird** [comment]
hi @juanise
you can use the following api method to browse the roambi rile system, the api response will include the the uid of the files. Hope this helps
https://github.com/Roambi/roambi-api-docs/blob/develop/user-guide/3.-Portals-Roambi-File-System-(RFS).md#read-portal-contents

**Comment by juanise** [comment]
Thank you charlesweird, what i really need to know is if I can create a completely new template with Roambi API or first I must go to publisher, create a template called juanise_template, then i get juanise_template_uid, source_file_uid, folder_uid, and finally call method
  POST /1/accounts/${ACCOUNT_UID}/files/analytics

to change juanise_template's data.

Thank you very much.

**Comment by charlesweird** [comment]
Right now creating a completely new template roambi file can only be done in the publisher on the browser. It is not supported via public API

**Comment by juanise** [comment]
That's a shame, will be this functionality implemented in any upcoming version?

Thanks again.

**Comment by kirvin** [comment]
We do not have any plans to introduce this type of functionality into the API at this time.  It is something we would like to do in the future, but the programmatic representation of a roambi template is very complex, and will be difficult at this time to translate it into a JSON representation that would be easy to use via the API.

It would be great to get some more detail around your use case for defining a new roambi file programmatically.  If you can, add a suggestion at our Roambi Ideas portal here:  https://support.roambi.com/hc/en-us/articles/202190454

**Comment by juanise** [comment]
Ok, thank you very much, we will try to define our use case and we will submit it to Roambi Ideas
