### ISSUE TITLE
Get published file uid

### ISSUE THREAD

**Issue by juanise** [Roambi/roambi-api-docs#11]
Hi everyone, i need to change permisions to a rbi file that I publish via API.
When i use the API method to publish the response is a JSON with a background publication job
Is there any posibility that this job contains the rbi's uid?
Maybe it is possible if job's status is complete and it have no exception:

thanks for your great job.

**Comment by charlesweird** [comment]
hi Juan
Currently the published rbi uid is not included in the job progress response json. If you are looking for a way to find the published rbi file's uid. After the publish job is completed without error, you can simply make a GET request to
https://api.roambi.com/1/accounts/`$ACCOUNT_UID`/files/info?path=`/$FOLDER_NAME/$FILE_NAME`
You should know the target folder path and the rbi file name when you publish the rbi. The server will reply a json containing the published rbi file info
{
    "uid": "5176db7884aea7...",
    "title": "My File",
    "created_at": "2013-04-23",
    "updated_at": "2013-04-24"
}
make sure you include "Authorization: Bearer `$ACCESS_TOKEN`" in the request header
Hope this helps

**Comment by juanise** [comment]
Yes it helps i didn't know that. Thank you very much.

**Comment by kirvin** [comment]
@juanise Thanks for your suggestion about returning the published file uid in the job response.  We will look into this as we continue to make enhancements to the API.
